name: Update BIDS validations

on:
  schedule:
    - cron: "0 4 * * *"  # ~12am eastern time
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch of BIDS-Dandisets to run BIDS validation on'
        type: choice
        options:
          - draft
          - basic_sanitization
        default: 'draft'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  _GITHUB_API_KEY: ${{ secrets._GITHUB_API_KEY }}

jobs:
  UpdateBIDSValidations:
    name: Update BIDS validations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: pip install dandi bids-validator-deno!=2.2.4

      - name: Run script on draft branches
        run: python scripts/update_bids_validations.py --branch ${{ github.event.inputs.branch || 'draft' }}

  NotifyOnFailure:
    runs-on: ubuntu-latest
    needs: [ UpdateBIDSValidations ]
    if: ${{ always() && needs.UpdateBIDSValidations.result == 'failure' }}
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "CI Failure: BIDS-Dandisets Dashboard Update"
          to: cody.c.baker.phd@gmail.com  # Add more with comma separation (no spaces)
          from: bids-dandisets
          body: "Please check the latest run of the BIDS-Dandisets BIDS validation: https://github.com/bids-dandisets/scripts/actions/workflows/update_bids_validations.yml"
