name: Update BIDS validations

on:
  schedule:
    - cron: "0 4 * * *"  # ~12am eastern time
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch of BIDS-Dandisets to run BIDS validation on'
        type: choice
        options:
          - draft
          - basic_sanitization
        default: 'draft'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  _GITHUB_API_KEY: ${{ secrets._GITHUB_API_KEY }}

jobs:
  UpdateBIDSValidations:
    name: Update BIDS validations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: pip install dandi

      - name: Run script on draft branches
        run: python scripts/update_bids_validations.py --branch ${{ github.event.inputs.branch || 'draft' }}
